Traceback (most recent call last):
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 75, in <module>
    fail_test()
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 68, in fail_test
    x = 1 / 0
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 178, in <module>
    long_running_test()
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 170, in long_running_test
    print(i, "seconds have passed")
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 170, in long_running_test
    print(i, "seconds have passed")
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 133, in check_time
    raise TimeoutError
TimeoutError
Traceback (most recent call last):
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 188, in <module>
    long_running_test()
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 170, in long_running_test
    print(i, "seconds have passed")
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 170, in long_running_test
    print(i, "seconds have passed")
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 133, in check_time
    raise TimeoutError
TimeoutError
Traceback (most recent call last):
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 189, in <module>
    long_running_test()
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 170, in long_running_test
    print(i, "seconds have passed")
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 170, in long_running_test
    print(i, "seconds have passed")
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 133, in check_time
    raise TimeoutError
TimeoutError
Traceback (most recent call last):
  File "code/Basic_Fuzzing.py", line 285, in <module>
    crash_if_too_long(s)
  File "code/Basic_Fuzzing.py", line 267, in crash_if_too_long
    raise ValueError
ValueError
Traceback (most recent call last):
  File "code/Basic_Fuzzing.py", line 335, in <module>
    hang_if_no_space(s)
  File "code/Basic_Fuzzing.py", line 317, in hang_if_no_space
    i += 1
  File "code/Basic_Fuzzing.py", line 317, in hang_if_no_space
    i += 1
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 133, in check_time
    raise TimeoutError
TimeoutError
Traceback (most recent call last):
  File "code/Basic_Fuzzing.py", line 380, in <module>
    collapse_if_too_large(long_number)
  File "code/Basic_Fuzzing.py", line 362, in collapse_if_too_large
    raise ValueError
ValueError
/)=04-?: <"?*?5658>6!%<!8/
'%,%\':,0\'918*143:*-2&35$06!((;<61<:6%!?6+-))/-;65-2.;"8>6-87 7:9)!+?"&)6"71*#.-+<2&:"*(!;-/:5"2%"1!5'
input.txt 1: parse error
input.txt 1: illegal character: '
input.txt 1: illegal character: :
input.txt 1: illegal character: '
input.txt 1: illegal character: :
input.txt 1: illegal character: &
input.txt 1: parse error
input.txt 1: illegal character: $
input.txt 1: parse error
input.txt 1: illegal character: :
input.txt 1: illegal character: ?
input.txt 1: parse error
input.txt 1: illegal character: &
input.txt 1: parse error
input.txt 1: illegal character: :

Start
0 seconds have passed
1 seconds have passed
2 seconds have passed
3 seconds have passed
Start
Start
408752631457291
